name: '@guardian/actions-source-analysis'
description: 'A GitHub action to analyse the usage of Source in a project'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
